APP_NAME = "F.E.D.O"
APP_VERSION = "v1.2"

ASSISTANT_NAME = "F.E.D.O"
USER_NAME = "товарищ"

AI_BACKEND = "lm_studio"
LM_STUDIO_URL = "http://127.0.0.1:8080/v1/chat/completions"

ASSISTANT_STYLE = "soviet"

VOICE_ENABLED = True
MICROPHONE_ENABLED = False

PUBLIC_MODE = True
PROFANITY_MODE = False

PROFANITY_TRIGGER_PHRASE = "ENABLE PROFANITY MODE"